#!/usr/bin/env bats
# Contract tests for skills/worktask/scripts/output-sections.sh — the generator that renders
# each stage's artifact H2 set from cache-lint.sh --allow-list into marked regions.
#   --print [--stage S]   rendered regions on stdout, exit 0; unknown stage exit 2
#   --check               exit 0 when every region matches; exit 1 naming drift, a missing
#                         region, or a duplicated/unbalanced marker pair
#   --write               repairs drift, appends a missing agent region, never inserts into
#                         the protocol
#   the real tree         --check is green (the make-test drift gate)
load "${BATS_TEST_DIRNAME}/../../lib/test_helper.bash"

SCRIPT="skills/worktask/scripts/output-sections.sh"
PROTO="skills/worktask/references/handoff-protocol.md"

setup() {
  WD="$(mk_tmpworkdir)"
  mkdir -p "$WD/repo/agents" "$WD/repo/$(dirname "$PROTO")"
  cp "$PLUGIN_ROOT"/agents/*.md "$WD/repo/agents/"
  cp "$PLUGIN_ROOT/$PROTO" "$WD/repo/$PROTO"
}

gen() { run bash "$PLUGIN_ROOT/$SCRIPT" --root "$WD/repo" "$@"; }

@test "repo: --check is green on the real agents/ and protocol (drift gate)" {
  run bash "$PLUGIN_ROOT/$SCRIPT" --check
  assert_success
  assert_output --partial "all regions match the allow-list"
}

@test "print: every stage renders its required set, sweep included, from the allow-list" {
  local stage heading n=0
  for stage in PL AR TL DV DR SR QA DC RE FN ST IR ET; do
    run bash "$PLUGIN_ROOT/$SCRIPT" --print --stage "$stage"
    assert_success
    assert_line "<!-- output-sections:begin stage=$stage -->"
    assert_line "<!-- output-sections:end stage=$stage -->"
    [[ "$output" == *'`## elicitation-sweep`'* ]] || fail "$stage: no sweep anchor rendered"
    while IFS=$'\t' read -r _ _ _ kind heading; do
      [ "$kind" = required ] || continue
      [[ "$output" == *"\`## $heading\`"* ]] || fail "$stage: required '$heading' not rendered"
      n=$((n + 1))
    done < <(bash "$PLUGIN_ROOT/skills/worktask/scripts/cache-lint.sh" --allow-list --stage "$stage")
  done
  [ "$n" -ge 13 ] || fail "non-vacuity: only $n required headings compared"
}

@test "print: optional lines appear only for stages with an optional row" {
  run bash "$PLUGIN_ROOT/$SCRIPT" --print --stage QA
  assert_success
  assert_output --partial '- Optional for QA: `## Visual Evidence`, `## Design Comparison`'
  run bash "$PLUGIN_ROOT/$SCRIPT" --print --stage DR
  assert_success
  refute_output --partial "Optional for DR"
  assert_output --partial "Optional in any stage"
}

@test "print: an unknown stage exits 2" {
  run bash "$PLUGIN_ROOT/$SCRIPT" --print --stage ZZ
  assert_failure 2
}

@test "usage: no mode, or --stage with --check, exits 2" {
  run bash "$PLUGIN_ROOT/$SCRIPT"
  assert_failure 2
  run bash "$PLUGIN_ROOT/$SCRIPT" --check --stage DV
  assert_failure 2
}

@test "drift: a hand edit inside a region fails --check naming file and key; --write repairs it" {
  gen --check
  assert_success
  sed 's/^- Required: `## files-changed`/- Required: `## approach`, `## files-changed`/' \
    "$WD/repo/agents/developer.md" > "$WD/dev" && cat "$WD/dev" > "$WD/repo/agents/developer.md"
  gen --check
  assert_failure 1
  assert_output --partial "agents/developer.md: stage=DV: drift"
  gen --write
  assert_success
  gen --check
  assert_success
  cmp -s "$WD/repo/agents/developer.md" "$PLUGIN_ROOT/agents/developer.md" \
    || fail "--write did not restore the generated bytes"
}

@test "drift: a hand-edited protocol table is caught (anti-vacuity on the table keys)" {
  sed 's/| ST | retrospective-N.md | `## decision`/| ST | retrospective-N.md | `## decisions`/' \
    "$WD/repo/$PROTO" > "$WD/p" && cat "$WD/p" > "$WD/repo/$PROTO"
  gen --check
  assert_failure 1
  assert_output --partial "handoff-protocol.md: table=required-sr-et: drift"
}

@test "missing: an agent without a region fails --check; --write appends one at EOF" {
  awk '/^<!-- output-sections:begin stage=QA -->$/ { exit } { print }' \
    "$PLUGIN_ROOT/agents/qa-engineer.md" > "$WD/repo/agents/qa-engineer.md"
  gen --check
  assert_failure 1
  assert_output --partial "agents/qa-engineer.md: stage=QA: missing region"
  gen --write
  assert_success
  assert_output --partial "appended stage=QA"
  tail -1 "$WD/repo/agents/qa-engineer.md" | grep -qx '<!-- output-sections:end stage=QA -->'
  gen --check
  assert_success
}

@test "missing: the protocol never gets an inserted region, --write fails instead" {
  grep -v 'output-sections:.* table=optional -->' "$PLUGIN_ROOT/$PROTO" > "$WD/repo/$PROTO"
  gen --write
  assert_failure 1
  assert_output --partial "table=optional: missing region"
  ! grep -q 'output-sections:begin table=optional' "$WD/repo/$PROTO"
}

@test "markers: a duplicated pair fails both --check and --write" {
  printf '<!-- output-sections:begin stage=ST -->\n<!-- output-sections:end stage=ST -->\n' \
    >> "$WD/repo/agents/stakeholder.md"
  gen --check
  assert_failure 1
  assert_output --partial "agents/stakeholder.md: stage=ST: duplicate marker pair"
  gen --write
  assert_failure 1
}

@test "markers: an unbalanced pair (end without begin) fails" {
  grep -v '^<!-- output-sections:begin stage=ET -->$' "$PLUGIN_ROOT/agents/ethics-reviewer.md" \
    > "$WD/repo/agents/ethics-reviewer.md"
  gen --check
  assert_failure 1
  assert_output --partial "stage=ET: unbalanced marker pair"
}

@test "source: an unreachable allow-list exits 2" {
  mkdir -p "$WD/copy"
  cp "$PLUGIN_ROOT/$SCRIPT" "$WD/copy/output-sections.sh"
  run bash "$WD/copy/output-sections.sh" --root "$WD/repo" --check
  assert_failure 2
  assert_output --partial "cache-lint.sh --allow-list cannot run"
}

@test "section-lint: the longest rendered region stays under the 1000-char cap" {
  local stage len max=0
  for stage in PL AR TL DV DR SR QA DC RE FN ST IR ET; do
    len="$(bash "$PLUGIN_ROOT/$SCRIPT" --print --stage "$stage" | wc -c | tr -d ' ')"
    [ "$len" -gt "$max" ] && max="$len"
  done
  [ "$max" -lt 1000 ] || fail "a rendered region is $max chars"
}

@test "contract: --self-test passes (smoke, NON-counting)" {
  run bash "$PLUGIN_ROOT/$SCRIPT" --self-test
  assert_success
  assert_output --partial "ALL PASS"
}
