#!/usr/bin/env bash
# attachments-preseed-test.sh — validates the pre-gate Conductor-attachments
# writer logic introduced by the fn-attachments-pre-gate fix.
#
# Usage:
#   attachments-preseed-test.sh --self-test
#       Runs all 3 test scenarios in a temp dir, cleans up on exit.
#       Exits 0 on all pass, 1 on any failure.
#
# Tests:
#   Test 1 (gated path): given DR + QA + state.json fixtures and a git repo,
#     invoke the writer logic; assert both files exist with expected fields
#     (DR verdict, QA verdict, current branch, conventional-commit type).
#   Test 2 (idempotency): run writer twice; diff outputs modulo <ISO_TS>
#     must be empty.
#   Test 3 (defensive default): run with developer-review.md ABSENT; assert
#     both files still produced with `verdict: unknown` in the review file.
#
# Fixture schema assumptions (RK-5 mitigation):
#   developer-review.md: must contain an "Approval Status" line and optionally
#     an "## Issues Found" section. The writer reads only these two patterns.
#   testing.md: must contain a "GO/NO-GO" (case-insensitive) or "verdict" line
#     and optionally an "## Results" section. The writer reads only these.
#   state.json: must be valid JSON with a `worktask_id` field.
#   git env: must be inside a git repo (or bare git config sufficient for
#     `git rev-parse --abbrev-ref HEAD` to return a branch name).
#
# Style: follows handoff-harness.sh (--self-test mode, fixture-based, exit codes).

set -euo pipefail

MODE="help"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --self-test) MODE="self-test"; shift ;;
    *) echo "unknown arg: $1" >&2; echo "usage: $0 --self-test" >&2; exit 2 ;;
  esac
done

if [[ "$MODE" != "self-test" ]]; then
  echo "usage: $0 --self-test" >&2
  exit 2
fi

# ---------- helpers ----------

pass() { echo "PASS: $*"; }
fail() { echo "FAIL: $*" >&2; exit 1; }

# Strip ISO timestamps for idempotency diff: replace ts: YYYY-MM-DDTHH:MM:SSZ
strip_ts() {
  sed 's/ts: [0-9T:Z-]\{20,\}/<ISO_TS>/g' "$1"
}

# ---------- writer function (mirrors SKILL.md step 4.9.1 logic) ----------
# Arguments: $1=workdir $2=worktask_id $3=branch $4=base_branch
# Reads fixtures from $1/.context/{developer-review.md,testing.md,planning-1.md}
# Writes to $1/.context/attachments/
run_writer() {
  local workdir="$1"
  local worktask_id="${2:-test-worktask}"
  local branch="${3:-feature/test}"
  local base_branch="${4:-main}"

  local uncommitted=3
  local upstream_line="There is no upstream branch yet."
  local commit_type="fix"

  # Resolve DR verdict (defensive default: verdict: unknown)
  local dr_verdict="verdict: unknown"
  local dr_concerns="(none flagged)"
  if [[ -f "$workdir/.context/developer-review.md" ]]; then
    local dr_match
    dr_match=$(grep -m1 "Approval Status" "$workdir/.context/developer-review.md" 2>/dev/null || true)
    if [[ -n "$dr_match" ]]; then
      dr_verdict="$dr_match"
    fi
    # Extract Issues Found section
    local issues
    issues=$(awk '/^## Issues Found/{found=1; next} found && /^## /{found=0} found{print}' \
      "$workdir/.context/developer-review.md" | grep -v '^$' | head -10 || true)
    if [[ -n "$issues" ]]; then
      dr_concerns=$(echo "$issues" | sed 's/^/- /')
    fi
  fi

  # Resolve QA verdict (defensive default: verdict: unknown)
  local qa_verdict="verdict: unknown"
  local qa_notes="(none)"
  if [[ -f "$workdir/.context/testing.md" ]]; then
    local qa_match
    qa_match=$(grep -im1 "GO/NO-GO\|verdict" "$workdir/.context/testing.md" 2>/dev/null || true)
    if [[ -n "$qa_match" ]]; then
      qa_verdict="$qa_match"
    fi
  fi

  local iso_ts
  iso_ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  mkdir -p "$workdir/.context/attachments"

  # Write PR instructions.md
  cat > "$workdir/.context/attachments/PR instructions.md" <<EOF
<!-- Generated by corpflow FN stage. worktask_id: ${worktask_id}, ts: ${iso_ts} -->

The corpflow worktask has finished and is ready to ship.

There are ${uncommitted} uncommitted changes.
The current branch is ${branch}.
The target branch is origin/${base_branch}.

${upstream_line}

The user requested a PR.

Follow these steps to create the PR:

- If you have any skills related to creating PRs, invoke them now. Instructions there should take precedence over these instructions.
- Run \`git diff\` to review uncommitted changes.
- Read \`.context/complete.md\` for the worktask summary, files changed, and stage timings — use it to draft the PR title and body.
- Commit format: \`<TYPE>[scope]: <Summary>\` per \`rules/git-conventions.md\` (Conventional Commits 1.0.0). Suggested type for this worktask: **${commit_type}** (derived from PL planning).
- Push to origin (set upstream if not yet tracked).
- Use the \`mcp__conductor__GetWorkspaceDiff\` tool to review the PR diff.
- Use \`gh pr create --base ${base_branch}\` to open the PR. Keep the title under 72 characters. Body sections: \`## Motivation\`, \`## Changes\`, \`## Notes\`. End body with a \`Closes #999\` line on its own line so the PR closes its linked issue on merge (resolved via the FN PR-issue-link validator). Describe ALL changes in the workspace diff, not only the most recent commit.
- Do NOT add "Generated with Claude Code" or "Co-Authored-By: Claude" footers.

If any step fails, ask the user for help.
EOF

  # Write Review request.md
  cat > "$workdir/.context/attachments/Review request.md" <<EOF
<!-- Generated by corpflow FN stage. worktask_id: ${worktask_id}, ts: ${iso_ts} -->

# Review guidelines

You are acting as a reviewer for code produced by an automated multi-stage
worktask. The worktask has already passed an internal Developer Review (DR)
and QA stage; your job is to catch what those stages missed.

## Worktask context

- Worktask ID: ${worktask_id}
- Branch: ${branch}  →  Target: origin/${base_branch}
- DR verdict: ${dr_verdict}   (\`.context/developer-review.md\`)
- QA verdict: ${qa_verdict}   (\`.context/testing.md\`)
- Summary: see \`.context/complete.md\` § Summary

## Focus areas (auto-extracted)

DR concerns the worktask surfaced but did not block on:
${dr_concerns}

QA observations worth a second look:
${qa_notes}

## When to flag a finding

1. It meaningfully impacts accuracy, performance, security, or maintainability.
2. It is discrete, actionable, and was introduced by this branch.
3. The original author would fix it if they were aware.
4. The bug does not rely on unstated assumptions about the codebase.
5. It is not just an intentional change.

If nothing meets the bar, return zero findings — do not invent issues to look thorough.

## Comment style

- One comment per distinct issue. Use a multi-line range only when needed.
- Use \` \`\`\`suggestion \` blocks ONLY for concrete replacement code; preserve exact leading whitespace; no commentary inside the block.
- One paragraph max per comment. Inline code via backticks; code blocks ≤ 3 lines.
- Tone: matter-of-fact, not accusatory; not flattering. No "Great job", no "Thanks for".
- Severity must match impact — do not over-claim.

## Getting the diff

Prefer \`mcp__conductor__GetWorkspaceDiff\` (start with \`stat: true\`, then request specific files).

Fallback when the tool is unavailable:

\`\`\`bash
MERGE_BASE=\$(git merge-base origin/${base_branch} HEAD)
git diff \$MERGE_BASE HEAD       # committed changes
git diff HEAD                    # uncommitted work in progress
\`\`\`

Review both outputs together. No need to mention which strategy you used.

## Output

Post inline comments via \`mcp__conductor__DiffComment\`. **One comment per unique issue.** Then write a top-level summary list:

\`\`\`
### #1 <Short title>
<One-paragraph explanation>
File: <path>

### #2 <Short title>
…
\`\`\`
EOF
}

# ---------- Test 1: gated path ----------
test_gated_path() {
  local td
  td=$(mktemp -d -t preseed-test1-XXXXXX)
  trap "rm -rf '$td'" RETURN

  mkdir -p "$td/.context"

  # Fixture: developer-review.md
  cat > "$td/.context/developer-review.md" <<'EOF'
# Developer Review

Approval Status: APPROVED — no blocking issues found.

## Issues Found

Minor: unused import in skills/worktask/SKILL.md line 3.

## Summary

Code quality acceptable.
EOF

  # Fixture: testing.md
  cat > "$td/.context/testing.md" <<'EOF'
# QA Testing

GO/NO-GO: GO — all 3 test scenarios passed.

## Results

Test 1 (gated path): PASS
Test 2 (idempotency): PASS
Test 3 (defensive default): PASS
EOF

  # Fixture: state.json
  cat > "$td/.context/state.json" <<'EOF'
{
  "version": 1,
  "worktask_id": "fn-attachments-pre-gate",
  "plan_file": ".context/planning-1.md",
  "platform": "all",
  "stages": { "PL": { "status": "completed", "verdict": "ok" } },
  "facts": { "files_modified": [], "tests_added": [], "decisions": [], "open_questions": [] },
  "handoffs": {}
}
EOF

  run_writer "$td" "fn-attachments-pre-gate" "feature/handoff-protocol" "master"

  # Assert both files exist
  [[ -f "$td/.context/attachments/PR instructions.md" ]] \
    || fail "Test 1: PR instructions.md missing"
  [[ -f "$td/.context/attachments/Review request.md" ]] \
    || fail "Test 1: Review request.md missing"

  # Assert PR instructions.md fields
  grep -q "feature/handoff-protocol" "$td/.context/attachments/PR instructions.md" \
    || fail "Test 1: PR instructions.md missing branch field"
  grep -q "origin/master" "$td/.context/attachments/PR instructions.md" \
    || fail "Test 1: PR instructions.md missing base branch field"
  grep -q "fix" "$td/.context/attachments/PR instructions.md" \
    || fail "Test 1: PR instructions.md missing conventional-commit type"
  grep -q "fn-attachments-pre-gate" "$td/.context/attachments/PR instructions.md" \
    || fail "Test 1: PR instructions.md missing worktask_id"

  # Assert Review request.md fields
  grep -q "DR verdict" "$td/.context/attachments/Review request.md" \
    || fail "Test 1: Review request.md missing DR verdict label"
  grep -q "Approval Status" "$td/.context/attachments/Review request.md" \
    || fail "Test 1: Review request.md missing DR verdict value"
  grep -q "QA verdict" "$td/.context/attachments/Review request.md" \
    || fail "Test 1: Review request.md missing QA verdict label"
  grep -q "GO/NO-GO" "$td/.context/attachments/Review request.md" \
    || fail "Test 1: Review request.md missing QA verdict value"
  grep -q "feature/handoff-protocol" "$td/.context/attachments/Review request.md" \
    || fail "Test 1: Review request.md missing branch"

  pass "Test 1 (gated path)"
}

# ---------- Test 2: idempotency ----------
test_idempotency() {
  local td
  td=$(mktemp -d -t preseed-test2-XXXXXX)
  trap "rm -rf '$td'" RETURN

  mkdir -p "$td/.context"

  cat > "$td/.context/developer-review.md" <<'EOF'
Approval Status: APPROVED
## Issues Found
EOF

  cat > "$td/.context/testing.md" <<'EOF'
GO/NO-GO: GO
## Results
All tests passed.
EOF

  # Run writer twice
  run_writer "$td" "idempotency-test" "feature/test" "main"
  # Snapshot first run (strip timestamps)
  strip_ts "$td/.context/attachments/PR instructions.md" > "$td/pr_run1.txt"
  strip_ts "$td/.context/attachments/Review request.md" > "$td/rv_run1.txt"

  # Small sleep to ensure timestamp would differ if not stripped
  sleep 1

  run_writer "$td" "idempotency-test" "feature/test" "main"
  strip_ts "$td/.context/attachments/PR instructions.md" > "$td/pr_run2.txt"
  strip_ts "$td/.context/attachments/Review request.md" > "$td/rv_run2.txt"

  # Diff must be empty (modulo timestamp)
  if ! diff -q "$td/pr_run1.txt" "$td/pr_run2.txt" >/dev/null; then
    diff "$td/pr_run1.txt" "$td/pr_run2.txt" >&2
    fail "Test 2: PR instructions.md not idempotent (diff non-empty after timestamp strip)"
  fi
  if ! diff -q "$td/rv_run1.txt" "$td/rv_run2.txt" >/dev/null; then
    diff "$td/rv_run1.txt" "$td/rv_run2.txt" >&2
    fail "Test 2: Review request.md not idempotent (diff non-empty after timestamp strip)"
  fi

  pass "Test 2 (idempotency)"
}

# ---------- Test 3: defensive default (DR artifact absent) ----------
test_defensive_default() {
  local td
  td=$(mktemp -d -t preseed-test3-XXXXXX)
  trap "rm -rf '$td'" RETURN

  mkdir -p "$td/.context"

  # Intentionally NO developer-review.md

  cat > "$td/.context/testing.md" <<'EOF'
GO/NO-GO: GO
EOF

  run_writer "$td" "defensive-default-test" "feature/test" "main"

  # Both files must still exist
  [[ -f "$td/.context/attachments/PR instructions.md" ]] \
    || fail "Test 3: PR instructions.md missing when DR artifact absent"
  [[ -f "$td/.context/attachments/Review request.md" ]] \
    || fail "Test 3: Review request.md missing when DR artifact absent"

  # Review request must contain `verdict: unknown` for DR
  grep -q "verdict: unknown" "$td/.context/attachments/Review request.md" \
    || fail "Test 3: Review request.md should contain 'verdict: unknown' when DR absent"

  pass "Test 3 (defensive default: DR absent)"
}

# ---------- main: self-test ----------
echo "--- attachments-preseed-test.sh --self-test ---"
test_gated_path
test_idempotency
test_defensive_default
echo "--- ALL TESTS PASSED ---"
exit 0
